### ISSUE TITLE
omniglot meta testing using data similar to Rand_X

### ISSUE THREAD

**Issue by FATE4869** [khurramjaved96/mrcl#13]
Hi guys, thank you for providing this code. That really helps me understand some implementation detail much better. Nevertheless, there are some parts in the code that still puzzles me. 
I am working on re-implementing the oml_omniglot experiment. If my understanding is correct, the Traj_X is generated from class(481:963) and Rand_X is from class(0:963). After training, your model should be able to do incremental testing which is classification task over class(481:963) and meta testing which is adapting to new class, i.e. class(0:481), in few shots. The question I have is since during training, you use Rand_X to update the RLN which means it already gain some knowledge about class(0:481). Then is it fair to do the meta testing on those classes?

**Comment by khurramjaved96** [comment]
Hi, 
Omniglot has ~1600 classes. The first 963 classes are accessed by setting background = True in the dataloader, whereas the last 600 are accessed setting background = False. 

Meta-training is done on the first 963 whereas meta-testing is done on the last 600. The meta-testing classes are not used in Traj_X or Rand_X. 

Dividing the first 963 meta-training classes into two sets is an implementation detail; if you checkout an older commit (Around July 1st), you would find an implementation that doesn't use this division and still gets similar results.

**Comment by FATE4869** [comment]
Hi,
Thank you for replying. I think that makes sense now.
