### ISSUE TITLE
Question on meta parameters

### ISSUE THREAD

**Issue by mmderakhshani** [khurramjaved96/mrcl#14]
Hi @khurramjaved96. 

Thanks for publishing your code. I have got a question regarding meta parameters (theta) optimization during your meta-training. I have explored your code and, let's say in oml_omniglot.py, I did not understand how did you optimize those parameters. Because before training, you freeze the weights of early layers which are actually theta parameters, and based on this evidence I believe that meta parameters would not be updated anymore. Am I correct?

**Comment by khurramjaved96** [comment]
The meta-parameters are only fixed in the inner loop. They are updated to minimize the meta-loss. 
 
In the code, theta is updated in line 273 of model/meta_learner.py because the self.optimizer object is initialized to optimize all the parameters of the model in line 28 of model/meta_learner.py.
