### ISSUE TITLE
Only half of classes used as query for outer loop in omniglot

### ISSUE THREAD

**Issue by sebamenabar** [khurramjaved96/mrcl#17]
Hi, when creating the complete omniglot iterator, [this line](https://github.com/khurramjaved96/mrcl/blob/76da0b2803651b0c292a9f1e5d9988b879380b40/datasets/task_sampler.py#L210)
```pyhton
self.task_sampler.add_complete_iteraetor(list(range(0, int(len(self.tasks)/2))))
```

when creating the query sampler, if I understood corrrectly, you make a subset of the first half of the omniglot classes.
Is this correct? This may cause just a small relaxation on the goal of not forgetting. If I want to train a more strict method should I change this to use all classes?

p.d: thanks for releasing the code and cool work!

**Comment by khurramjaved96** [comment]
Hi, 

Yes, you can train the more strict version by changing this to all classes. As long as the inner loop is learning more than one class incrementally, everything should work out fine. (I ran some experiments learning 5 classes using 3 example per class -- 15 inner updates -- and the results were similar to those achieved with this relaxation).

**Comment by khurramjaved96** [comment]
I also pushed "oml_omniglot_paper.py" -- an OML implementation that does not make a subset of first half of the classes.

**Comment by sebamenabar** [comment]
thanks!
