### ISSUE TITLE
Two issues in the latest version of the code (args['memory'] and bn_training)

### ISSUE THREAD

**Issue by adityarawal** [khurramjaved96/mrcl#18]
Congratulations on the impressive work! 

I am using the the latest version of the code (05 July, 2020) for the Omniglot experiment. Training the model works fine. However, when I try to evaluate the trained model by using the following command: 

python evaluate_omniglot.py --model-path path_to_model/learner.model --name Omniglot_evaluation/  --schedule 10:50:100:200:600

I get the following error: 

Traceback (most recent call last):
  File "evaluate_omniglot.py", line 203, in <module>
    main()
  File "evaluate_omniglot.py", line 151, in main
    for mem_size in [args['memory']]:
KeyError: 'memory'

I fixed this by adding the following line to the file mrcl/configs/classification/class_parser_eval.py
self.add('--memory', type=int, help='I dont know what this argument is used for', default=0)

When I re-run the code with the above hack, it proceeds further but then gives a new error:  

File "evaluate_omniglot.py", line 179, in main
    logits_q = maml(img, vars=None, bn_training=False, feature=False)
Unknown argument: 'bn_training' 

I removed 'bn_training' and 'feature' as arguments to fix the above errors. 

Could you please confirm whether these fixes for the two errors above are correct? 
Also, could you describe what args['memory'] is supposed to do?

Thanks,
Aditya Rawal

**Comment by khurramjaved96** [comment]
Hi Aditya, 

Thanks for bringing this to my attention. Seems like I had not pushed the updated evaluation script when I updated the code. Just pushed the updated evaluation script which should work fine. Let me know if it doesn't. 

Best, 
Khurram
