### ISSUE TITLE
Unable to run benchmark

### ISSUE THREAD

**Issue by SMHendryx** [Khurramjaved96/mrcl#19]
Hi, I've set up an environment using the `requirements.txt` and downloaded your pretrained model but am unable to run the `evaluate_omniglot.py` script. 

Calling `python evaluate_omniglot.py --model-path pretrained_models/omniglot_oml.model --name Omniglot_evaluation/  --test`
produces:
```
All args =  {'my_config': 'configs/regression/empty.ini', 'steps': 200000, 'gpus': 1, 'rank': 0, 'tasks': [1], 'meta_lr': [0.0001], 'update_lr': [0.01], 'update_step': [10], 'dataset': 'omniglot', 'no_reset': False, 'seed': [90], 'name': 'Omniglot_evaluation/', 'path': '/Users/sean/data/omniglot', 'schedule': '200', 'scratch': False, 'reset': False, 'test': True, 'iid': False, 'runs': 50, 'model_path': ['pretrained_models/omniglot_oml.model']}
{'seed': 90, 'my_config': 'configs/regression/empty.ini', 'steps': 200000, 'gpus': 1, 'rank': 0, 'tasks': 1, 'meta_lr': 0.0001, 'update_lr': 0.01, 'update_step': 10, 'dataset': 'omniglot', 'no_reset': False, 'name': 'Omniglot_evaluation/', 'path': '/Users/sean/data/omniglot', 'schedule': '200', 'scratch': False, 'reset': False, 'test': True, 'iid': False, 'runs': 50, 'model_path': 'pretrained_models/omniglot_oml.model'}
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
Total classes =  658
[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5]
Total classes =  658
/Users/sean/repositories/continual-learning/mrcl/.env/lib/python3.6/site-packages/torch/serialization.py:435: SourceChangeWarning: source code of class 'model.learner.Learner' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
Traceback (most recent call last):
  File "evaluate_omniglot.py", line 186, in <module>
    main()
  File "evaluate_omniglot.py", line 86, in main
    maml = load_model(args, config)
  File "evaluate_omniglot.py", line 30, in load_model
    net.reset_vars()
  File "/Users/sean/repositories/continual-learning/mrcl/model/learner.py", line 77, in reset_vars
    if var.adaptation is True:
AttributeError: 'Parameter' object has no attribute 'adaptation'
```

Also, the download omniglot functionality didn't seem to work, but I was able to get around that by downloading manually from the same source.

Thanks

**Comment by kjaved0** [comment]
Hi, 
You might be loading the old pre-trained models. The code-base has changed quite a lot since then and only the most recent models can be loaded. Try using the model in: Google drive -> New_omniglot_models -> any one of the 8 folders -> learner.model. 

In-case you want to use old models, you would have to checkout an older commit of the repo (Try the 3rd september, 2019 commit).

**Comment by SMHendryx** [comment]
Thanks! I downloaded 1_1 the code seems to be doing something now. A couple other questions:
1. Do you know the best learning rate to avoid having to run the learning rate sweep that would reproduce the first row  in Table 2?
2. Is this the correct command for reproducing the first row in Table 2? `python evaluate_omniglot.py --model-path pretrained_models/learner.model --name Omniglot_evaluation/  --test --rln 6 --schedule 200 --runs 10`

**Comment by kjaved0** [comment]
1. I don't remember. It'd be best to run the sweep; you should be able to remove the smallest and largest two from the sweep. 
2. I think the right command would be:  "python evaluate_omniglot.py --model-path path_to_model/learner.model --name Omniglot_evaluation/  --schedule 50." This would give you both the train and the test accuracy. Table 2 reports the ~~train~~ test accuracy. I would expect the new model to perform much better than the results in the paper (85%+)

**Comment by SMHendryx** [comment]
That makes sense looking more closely at Table 2. And yes it looks like the new model is doing much better. Thanks for the quick feedback!
