### ISSUE TITLE
Trained models

### ISSUE THREAD

**Issue by nshervt** [Khurramjaved96/mrcl#21]
Hello,

I was looking at the trained models you have provided in the google drive directory. I was wondering what is the difference between old and new omniglot models and also what is the difference b/w the models provided in the `New_omniglot_models` folder, named as `1_1` through `1_8`. In conclusion, which one should I use to evaluate the model?

Thanks!🙂

**Comment by kjaved0** [comment]
Hi, 

The old models were used for the results in the paper but are not compatible with the current code. If you want to use the old model, you will have to checkout an old commit (A commit around August 2019 should work). 

The new models should be compatible with the current code. The models 1_1 to 1_8 are 8 models trained using same parameters but for different seeds. You can use any of them. The motivation to train 8 models was to show that the meta-training procedure has low variance, and learns well across seeds. 

Best, 
Khurram

**Comment by nshervt** [comment]
Thanks for the prompt response!
