### ISSUE TITLE
IndexError in Omniglot Experiments

### ISSUE THREAD

**Issue by pybeebee** [khurramjaved96/mrcl#3]
I am getting an IndexError in the meta_learner.py file, MetaLearingClassification class, forward() method, [lines 252-276.](https://github.com/khurramjaved96/mrcl/blob/408d8c2637ad0634d75e954d27aaf494d09c67c1/model/meta_learner.py#L252-L276)

When I run the command
`python mrcl_classification.py --rln 6 --update_lr 0.03 --name mrcl_omniglot --update_step 20 --steps 15000`

I receive the following error message:

> IndexError: index 19 is out of bounds for dimension 0 with size 19

I have attempted to fix by:

1. Initializing meta_losses and accuracy_meta_set as lists of floats rather than ints:
```
# Original
meta_losses = [0 for _ in range(self.update_step)]
accuracy_meta_set = [0 for _ in range(self.update_step)]

# My Change
meta_losses = [0.0 for _ in range(self.update_step)]
accuracy_meta_set = [0.0 for _ in range(self.update_step)]
```

2. Reducing the for loop index by 1
```
# Original
for k in range(1, self.update_step):

# My Change
for k in range(1, self.update_step-1):
```

Is this change a correct interpretation of the MRCL method?

Can you please comment on this issue?

Thank you.

**Comment by khurramjaved96** [comment]
Hi, 
Adding `self.update_step = len(x_traj)` before `meta_losses = [0 for _ in range(self.update_step)]`  should fix the issue for now. (Or you can use `--update_step 10` during training). 

I suspect some of the changes I made to the repo later have broken things. I plan to revisit the repo and update and fix these issues next week.
