### ISSUE TITLE
Layer widths

### ISSUE THREAD

**Issue by jlindsey15** [khurramjaved96/mrcl#7]
Hi, thanks for making this code available!  In the modelfactory file, the architectures the sinusoidal regression problem have one extra wide layer in them (for the 9-layer feedforward model, layer 6 is 3x as wide).  Is this intended?  I couldn't find mention of this in the paper, but I might be misunderstanding something in the paper and/or the code.

**Comment by khurramjaved96** [comment]
Hi, 
If I recall correctly, I was testing if having a larger representation space results in a noticeable difference in performance -- it does not. You should be able to safely make layer 6 as wide as others.  

I think the model I used for the results in the paper did not use the 3x wide layer. I'll check and update the paper if this is not the case.

**Comment by jlindsey15** [comment]
Thanks!  If you wouldn't mind letting me know once you've checked, I'd appreciate it -- I've been using some of this code for a project I'm working on and it would be great to use an architecture consistent with what was used in your paper.

**Comment by khurramjaved96** [comment]
I checked the logs files -- **all layers are 400**. The appendix of the paper says 300; probably a typo.
